# Generated by Django 6.1 on 2026-09-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nombre',), 'verbose_name': 'Categoría de Productos', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
